name: projects

on: repository_dispatch

jobs:

  server:
    if: github.event.client_payload.job == 'server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Server
        working-directory: ./apps/server
        run: ./gradlew clean build

  client:
    if: github.event.client_payload.job == 'client'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Client
        working-directory: ./apps/client
        run: ./gradlew clean build